# proxy.yaml

basepath: "/v1/hipster"
operations:
- id: echo
  http_match:
  - path_template: "/echo"
    method: GET
- id: get-method
  http_match:
  - path_template: "/get/"
    method: GET

target:
  target_server_id: products

