# proxy.yaml

basepath: "/v2/hipster"
operations:
- id: products
  http_match:
  - path_template: "/apigeehipster/products"
    method: GET
- id: product-detail
  http_match:
  - path_template: "/apigeehipster/products/*"
    method: GET

target:
  target_server_id: products

